spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/deepkathon
    username: root
    password: 123qwe
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  #show '?' in sql in console